disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- vertical_whitespace
- line_length
- todo

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- StackOverflowQuestions/Networking/Reachability.swift
