disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- vertical_whitespace
- line_length
- todo
- block_based_kvo

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- StackOverflow/Networking/Reachability.swift
