language: objective-c
osx_image: xcode10
xcode_workspace: StackOverflow.xcworkspace
xcode_scheme: StackOverflow
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
xcode_sdk: iphonesimulator12.0
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO | xcpretty
